# fly.toml app configuration file generated for wgit-search-engine on 2024-02-15T13:11:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wgit-search-engine'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
